language: generic
osx_image: xcode10.2

cache:
  directories:
  - Carthage

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8

  - IOS_FRAMEWORK_SCHEME="SwiftQueue iOS"
  - MACOS_FRAMEWORK_SCHEME="SwiftQueue macOS"
  - TVOS_FRAMEWORK_SCHEME="SwiftQueue tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="SwiftQueue watchOS"

  - WORKSPACE="SwiftQueue.xcodeproj"
  - DESTINATION="arch=x86_64"

matrix:
    include:
        - os: osx
          env: TYPE="DANGER"
        - os: osx
          env: TYPE="CARTHAGE"
        - os: osx
          env: TYPE="SPM"
        - os: osx
          env: TYPE="XCODE"
        - os: osx
          env: TYPE="POD"
        - os: linux
          env: TYPE="LINUX"   
          dist: trusty
          sudo: required

before_install:
  - if [ $TYPE == "DANGER" ]; then
      brew install swiftlint;
      bundle install --path vendor/bundle;
    fi
  - if [ $TYPE == "POD" ]; then
      gem install cocoapods --pre;
      pod setup --silent;
    fi

install:
  - if [ $TYPE == "Linux" ] ; then 
      eval "$(curl -sL https://swiftenv.fuller.li/install.sh)";
    fi

script:

  - if [[ `uname` == "Darwin" ]] ; then
      set -o pipefail;
      xcodebuild -version;
      xcodebuild -showsdks;
    fi

  - if [ $TYPE == "DANGER" ]; then
      bundle exec danger;
    fi

  - if [ $TYPE == "XCODE" ]; then
      carthage bootstrap --platform mac --cache-builds;
      xcodebuild -project "$WORKSPACE" -scheme "$MACOS_FRAMEWORK_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test -enableCodeCoverage YES | xcpretty;
    fi

  - if [ $TYPE == "CARTHAGE" ]; then
      carthage bootstrap --cache-builds;
      carthage build --no-skip-current --cache-builds;
    fi

  - if [ $TYPE == "SPM" ]; then
      swift test;
    fi

  - if [ $TYPE == "POD" ]; then
      pod lib lint;
    fi

  - if [ $TYPE == "LINUX" ]; then
      swiftenv install swift-5.0;
      swift test;
    fi

after_success:
  - if [ $TYPE == "XCODE" ]; then
      bash <(curl -s https://codecov.io/bash);
    fi